name: Python CI with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run students' tests
      run: |
        pytest --cov=src --cov-report=json tests/

    - name: Read code coverage over students' tests
      run: |
        cat coverage.json | python -c "import sys, json; print(json.load(sys.stdin)['totals']['percent_covered'])"

    - if: "$(date +%Y-%m-%d)" > "${{ env.HOMEWORK_DEADLINE }}"
      name: Run master tests
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.BIG_SECRET_PASSWORD }}" \
        --output tests_master/test_person_master.py tests_master/encrypted_test_person_master.py.gpg
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.BIG_SECRET_PASSWORD }}" \
        --output tests_master/test_calculator_master.py tests_master/encrypted_test_calculator_master.py.gpg
        pytest tests_master/

    - if: "$(date +%Y-%m-%d)" < "${{ env.HOMEWORK_DEADLINE }}"
      name: Don't run master tests
      run: |
        echo "Deadline has not been reached yet, so we do not use the master tests to evaluate"
