name: Python CI with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HOMEWORK_DEADLINE: "2025-10-01"  # Set the homework deadline here with this format: "<Year>-<Month>-<Day>"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install pylint
        pip install -r requirements.txt

    - name: Run students' tests
      run: |
        pytest --cov=src --cov-report=json tests/

    - name: Read code coverage over students' tests
      run: |
        cat coverage.json | python -c "import sys, json; print(json.load(sys.stdin)['totals']['percent_covered'])"
    
    - name: Read the students' PEP8 score with pylint
      run: |
        pylint src/ --fail-under=8.0 || true  # Allow pylint to run even if it fails
        pylint_score=$(pylint src/ | grep -E 'Your code has been rated at' | awk '{print $7}' | cut -d '/' -f 1)
        echo "Pylint Score: ${pylint_score}"

    - name: Get current date
      id: date
      run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Run master tests if we are after the deadline
      if: ${{ steps.date.outputs.current_date > env.HOMEWORK_DEADLINE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.BIG_SECRET_PASSWORD }}" \
        --output tests_master/test_person_master.py tests_master/encrypted_test_person_master.py.gpg
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.BIG_SECRET_PASSWORD }}" \
        --output tests_master/test_calculator_master.py tests_master/encrypted_test_calculator_master.py.gpg
        pytest tests_master/
